title: Milind Juttiga
url: "https://milindtheengineer.github.io"
baseurl: "/home"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Theme researcher deployed using github pages"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/home/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
