title: Milind Juttiga
author: Milind Juttiga
description: Software Engineer at Meta working on distributed systems and infrastructure.
url: "https://milindtheengineer.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/milindtheengineer"
footer_text: "Milind Juttiga"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Projects"
   link: "projects"
 - name: "Contact"
   link: "contact"
